### ISSUE TITLE
train and val set overlaps?

### ISSUE THREAD

**Issue by dylansun** [stdcoutzyx/DeepID_FaceClassify#4]
As mentioned in the readme file:
- Choose first 5 imgs as validate set.
- Choose the 5th to 25th imgs as the train set.

The 5th img is both in train and val set?

**Comment by stdcoutzyx** [comment]
Hi, @dylansun , train and val set do not overlap. the first five means 0,1,2,3,4... programmers starts from zero..

**Comment by dylansun** [comment]
@stdcoutzyx yeah, catch the point. lol~
